import 'classnames'
import 'react'
import 'react-dom'
import 'react-redux'
import 'react-router'
import 'redux'
import 'redux-observable'
import 'reselect'

import 'rxjs/Observable'
import 'rxjs/add/operator/delay'
import 'rxjs/add/operator/map'
